version: '3.8'

services:
  db_user:
    container_name: mysql_db_user
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_user:/var/lib/mysql

  db_product:
    container_name: mysql_db_product
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_product_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_product:/var/lib/mysql

volumes:
  mysql_data_user:
  mysql_data_product:
