spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ${POSTS_ROUTE_URI:http://localhost:8087}
          predicates:
            - Path=/rest/product/**

        - id: product-service
          uri: ${POSTS_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true