spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ${POSTS_ROUTE_URI:http://localhost:8087}
          predicates:
            - Path=/rest/product/**

        - id: user-service
          uri: ${POSTS_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/auth/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8181/eureka/